version: '2'
services:
  bank:
    image: 'bank:v1'
  cart:
    image: 'cart:v1'
  products:
    image: 'products:v1'

  purchase:
    image: 'purchase:v1'
    links:
      - cart:cart.dev
      - bank:bank.dev
      - products:products.dev

  backend-tests:
    image: 'banking-spec:v1'
    links:
      - cart:cart.dev
      - bank:bank.dev
      - products:products.dev
      - purchase:purchase.dev
  gateway:
    image: 'banking-gateway:v1'
    build:
      context: './banking_gateway'
    ports:
      - "8085:80"
    links:
      - products:products.dev
  system-tests:
    image: 'banking-system-spec:v1'
    build:
      context: './spec'
    links:
      - gateway:gateway.dev
      - products:products.dev
    volumes:
      - "./spec:/usr/src/app/spec"
