version: '2'
services:
  bank:
    image: 'bank:v1'
    build:
      context: './bank'
    ports:
      - "8082:80"
    volumes:
      - "./bank:/go/src/github.com/dugancathal/gobanking/bank"
    command: "go run src/github.com/dugancathal/gobanking/bank/main.go"
  cart:
    image: 'cart:v1'
    build:
      context: './cart'
    ports:
      - "8083:80"
    volumes:
      - "./cart:/go/src/github.com/dugancathal/gobanking/cart"
    command: "go run src/github.com/dugancathal/gobanking/cart/main.go"
  products:
    image: 'products:v1'
    build:
      context: './products'
    ports:
      - "8081:80"
    volumes:
      - "./products:/go/src/github.com/dugancathal/gobanking/products"
    command: "go run src/github.com/dugancathal/gobanking/products/main.go"
  purchase:
    image: 'purchase:v1'
    build:
      context: './purchase'
    ports:
      - "8084:80"
    links:
      - cart:cart.dev
      - bank:bank.dev
      - products:products.dev
    volumes:
      - "./purchase:/go/src/github.com/dugancathal/gobanking/purchase"
    command: "go run src/github.com/dugancathal/gobanking/purchase/main.go"

  rspec:
    image: 'banking-spec:v1'
    build:
      context: './spec'
    links:
      - cart:cart.dev
      - bank:bank.dev
      - products:products.dev
      - purchase:purchase.dev
    volumes:
      - "./spec:/usr/src/app/spec"
