version: '2'
services:
  bank:
    image: 'bank:v1'
    build:
      context: '${BACKEND_DIR}/bank'
    ports:
      - "8082:80"
    volumes:
      - "${BACKEND_DIR}/bank:/go/src/github.com/dugancathal/gobanking/bank"
    command: "go run src/github.com/dugancathal/gobanking/bank/main.go"
  cart:
    image: 'cart:v1'
    build:
      context: '${BACKEND_DIR}/cart'
    ports:
      - "8083:80"
    volumes:
      - "${BACKEND_DIR}/cart:/go/src/github.com/dugancathal/gobanking/cart"
    command: "go run src/github.com/dugancathal/gobanking/cart/main.go"
  products:
    image: 'products:v1'
    build:
      context: '${BACKEND_DIR}/products'
    ports:
      - "8081:80"
    volumes:
      - "${BACKEND_DIR}/products:/go/src/github.com/dugancathal/gobanking/products"
    command: "go run src/github.com/dugancathal/gobanking/products/main.go"
  purchase:
    image: 'purchase:v1'
    build:
      context: '${BACKEND_DIR}/purchase'
    ports:
      - "8084:80"
    links:
      - cart:cart.dev
      - bank:bank.dev
      - products:products.dev
    volumes:
      - "${BACKEND_DIR}/purchase:/go/src/github.com/dugancathal/gobanking/purchase"
    command: "go run src/github.com/dugancathal/gobanking/purchase/main.go"

  rspec:
    image: 'banking-spec:v1'
    build:
      context: '${BACKEND_DIR}/spec'
    links:
      - cart:cart.dev
      - bank:bank.dev
      - products:products.dev
      - purchase:purchase.dev
    volumes:
      - "${BACKEND_DIR}/spec:/usr/src/app/spec"

  gateway:
    image: 'banking-gateway:v1'
    build:
      context: './banking_gateway'
    ports:
      - "8085:80"
    links:
      - products:products.dev
  system-tests:
    image: 'banking-system-spec:v1'
    build:
      context: './spec'
    links:
      - gateway:gateway.dev
      - products:products.dev
    volumes:
      - "./spec:/usr/src/app/spec"
